### ISSUE TITLE
DB Error

### ISSUE THREAD

**Issue by amiremami** [intrudir/BypassFuzzer#6]
Hi, I wanted to know if this error is related to your script or something is not ok on my end? I was trying to launch it in docker.

root@220707b5dbed:/function# python3 /function/BypassFuzzer/bypassfuzzer.py -u https://www.example.com

```
Traceback (most recent call last):
  File "/function/BypassFuzzer/bypassfuzzer.py", line 230, in <module>
    Fuzzer = BypassFuzzer(
  File "/function/BypassFuzzer/core/fuzzer/fuzzer.py", line 48, in __init__
    self.db_handler = DatabaseHandler(self.db_dir, db_name)
  File "/function/BypassFuzzer/core/fuzzer/db_handler.py", line 14, in __init__
    self.conn = sqlite3.connect(db_path)
sqlite3.OperationalError: unable to open database file
```

**Comment by intrudir** [comment]
Hi, i cant seem to reproduce the issue. Have you tried running it outside of docker and get the same problem?

**Comment by amiremami** [comment]
@intrudir 

Yes, it seems this happened in the new update. 

Am I doing something wrong here?

`python3 /root/BypassFuzzer/bypassfuzzer.py -u https://snpi.dell.com/`

![image](https://github.com/user-attachments/assets/cd162814-d56a-4762-9de5-d0bf3ac8ada5)

**Comment by amiremami** [comment]
Ok, so this how I did it to reproduce:

1. I got a fresh Ubuntu 22.04 server

And I installed it without:
```
python3 -m venv .venv
source .venv/bin/activate
```

```
git clone https://github.com/NetSPI/BypassFuzzer.git
cd BypassFuzzer
python3 -m pip install -r requirements.txt
cd
python3 /root/BypassFuzzer/bypassfuzzer.py -u https://snpi.dell.com/
```

**Comment by intrudir** [comment]
Hi, if youre not going to use the virtual environment, then you'll need to make sure all the dependencies are available on your system-level python.

so just do 
```bash
python3 -m pip install -r requirements.txt
```

It sounds like you arent familiar with virtual environments, so just incase you aren't, the purpose of
```bash
python3 -m venv .venv
source .venv/bin/activate
```

is to create a virtual environment. This is kinda like a little containerized python. You can install dependencies, and make all kinds of changes, and pretty much blow it up. If you ever need to start over, you just remove it and start over:
```
rm -rf .venv
python3 -v venv .venv

# and then activate the new env
source .venv/bin/activate
```

If you dont use a venv, that means youll need to much with dpeendencies on your OS level python. If something breaks in other scripts because of this, its a little harder to fix. Hope this makes sense!

**Comment by amiremami** [comment]
Hey, thank you so much : ) Yes, I already installed them with

`python3 -m pip install -r requirements.txt`

Yes, the above steps are the only steps I have done after getting a fresh vps. Didn't do it in a docker. I can give you access to a fresh server if you want, so you can see.

**Comment by intrudir** [comment]
@amiremami Sure. I can drop you a public key and you can grant me access. Are you on discord? Send me a friend request and DM and i will help troubleshoot. find me the same name @intrudir

**Comment by intrudir** [comment]
The issue was running the tool via the absolute path instead of from inside the dir (like im used to hehe)

The script relied on relative path to interactions db directory. This has been fixed via https://github.com/intrudir/BypassFuzzer/commit/1af0bb3647d39c12bf82a48e3ad8472bb61992c8

thanks!
